name: Audit
on: [push, pull_request]

env:
  HUSKY: 0
  node-version: lts/*

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Audit
        run: yarn audit
